### ISSUE TITLE
Carbon Aware SDK Lifecycle Stage Change Request Incubation > Graduated.

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/oc#79]
The Carbon Aware SDK Project team believe the project is now considered mature and stable, and is supported by an active community. Therefore we are requesting a Lifecycle Stage Change Request from Incubation to Graduated. 

This issue documents the project's fulfilment of the [necessary criteria to Graduate. ](https://oc.greensoftware.foundation/project-lifecycle.html#graduated)

The project must meet the Incubation requirements:

- [x] Have a representative of at least one GSF member company participating, who is a WG attendee who will champion the project, volunteer to run it as project lead and share updates at the WG = @vaughanknight Vaughan Knight (Microsoft), Project Lead
- [x] Have an assigned GSF PM = @Sophietn Sophie Trinder (Green Software Foundation), Project Manager
- [x] Project name should not be trademarked and should have the approval of GSF marketing

The project must meet the Graduated Acceptance Criteria:

- [x] Have a active set of contributing members from at least two member organisations = [Appointments](https://github.com/Green-Software-Foundation/carbon-aware-sdk?tab=readme-ov-file#appointments) from 4 member organisations. 
- [x] [Have a public GitHub repo](https://github.com/Green-Software-Foundation/carbon-aware-sdk) with clear project documentation on
  - [x] [Project overview (ReadMe)](https://github.com/Green-Software-Foundation/carbon-aware-sdk?tab=readme-ov-file#carbon-aware-sdk)
  - [x] [How to contribute (contributing.md)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/CONTRIBUTING.md)
  - [x] [End User Guide (enablement.md)](https://carbon-aware-sdk.greensoftware.foundation/docs/overview/enablement)
  - [x] [Test coverage](https://carbon-aware-sdk.greensoftware.foundation/docs/overview/tests)
  - [x] [Fit within GSF Theory of Change](https://github.com/Green-Software-Foundation/carbon-aware-sdk?tab=readme-ov-file#carbon-aware-sdk)
- [x] Have made a [release deployment](https://carbon-aware-sdk.greensoftware.foundation/blog), even a ‘developer preview’
- [x] Evidence of usefulness through real world use cases in the production environment, including testimonials[ (adopters.md)](https://carbon-aware-sdk.greensoftware.foundation/docs/overview/adopters)
- [x] Have 100% of the applicable criteria for the Open SSF Best Practice Badge [(security.md)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/SECURITY.md)
- [x] Have an [incident process](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/468#issuecomment-1953705710) agreed with GSF PM
- [x] Have GSF processes set up including
  - [x] [Project meetings](https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/17137665/Opensource+Carbon+Aware+SDK) and [mailing list]([carbon-aware-sdk@greensoftware.foundation](mailto:carbon-aware-sdk@greensoftware.foundation))
  - [x] Provide [regular updates](https://github.com/Green-Software-Foundation/opensource-wg/issues/48) to the relevant WG
  - [x] Have [defined OKRs](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/468#issuecomment-1956889169) agreed by the GSF PM

**Comment by Willmish** [comment]
Approved to share with rest of Oversight Committee to review for graduation from Incubation stage to Graduated under the Project Lifecycle https://oc.greensoftware.foundation/project-lifecycle.html#graduated . Thanks @Sophietn !
